version: "3"

services:
    mydb:
        container_name: marketplace_db
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: qwerty
            POSTGRES_DB: marketplace
            POSTGRES_USER: postgres
        ports: 
            - 5434:5432
    redis:
        container_name: redis_store
        image: "redis:alpine"
        restart: always
        ports:
            - 6379:6379

    redis-commander:
        container_name: redis_gui
        image: rediscommander/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - "8081:8081"
        depends_on:
            - redis