version: "3"

services:
    mydb:
        container_name: marketplace_db
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
        ports: 
            - ${POSTGRES_PORT}
        env_file: 
            - .env
    redis:
        container_name: redis_store
        image: "redis:alpine"
        restart: unless-stopped
        ports:
            - ${REDIS_PORT_DOCKER}
        env_file: 
            - .env

    redis-commander:
        container_name: redis_gui
        image: rediscommander/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=${REDIS_HOSTS}
        ports:
            - "8081:8081"
        depends_on:
            - redis