version: "3"

services:
    mydb:
        container_name: marketplace_db
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: qwerty
            POSTGRES_DB: marketplace
            POSTGRES_USER: postgres
        ports: 
            - 5434:5432